---
title: Oath of Iron
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: An Ironsworn Blog
url: old-guard-games.github.io
baseurl: "/oath-of-iron"
author:
  name: the_zenith_
  email: zenithmods@gmail.com
permalink: "/posts/:slug/"
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
paginate: 3
paginate_path: "/page:num/"
twitter:
  username: the_zenith_
  card: summary
facebook:
  app_id: 
  publisher: 
  admins: 
logo: "/assets/img/logo.jpg"
social:
  links:
  - https://twitter.com/the_zenith_
  - https://www.github.com/Zenith-One
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
sass:
  style: compressed
  sourcemap: never
